version: 0.2

artifacts:
  files:
    - '**/*'
  name: deploy.zip

phases:
  post_build:
    commands:
      - echo "Zipping files for Elastic Beanstalk deployment..."
      - zip -r deploy.zip . -x "*.git*"  # Exclude .git files
      - echo "Uploading deployment package to S3..."
      - aws s3 cp deploy.zip s3://my-eb-bucket/deploy.zip
      - echo "Creating a new application version in Elastic Beanstalk..."
      - aws elasticbeanstalk create-application-version --application-name my-eb-app --version-label v1 --source-bundle S3Bucket=my-eb-bucket,S3Key=deploy.zip
      - echo "Updating the Elastic Beanstalk environment..."
      - aws elasticbeanstalk update-environment --environment-name my-eb-environment --version-label v1
